// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lab-serverless/app"
	"lab-serverless/app/scf"
	"lab-serverless/app/scf/controller"
	"lab-serverless/app/scf/service"
	"lab-serverless/common"
)

// Injectors from wire.go:

func App(config common.Config) (*app.App, error) {
	engine := app.HttpServer(config)
	db, err := app.InitializeDatabase(config)
	if err != nil {
		return nil, err
	}
	dependency := &service.Dependency{
		Config: config,
		Db:     db,
	}
	index := service.NewIndex(dependency)
	controllerDependency := &controller.Dependency{
		Db:           db,
		IndexService: index,
	}
	controllerIndex := controller.NewIndex(controllerDependency)
	user := controller.NewUser(controllerDependency)
	scfDependency := &scf.Dependency{
		Index: controllerIndex,
		User:  user,
	}
	routes := scf.NewRoutes(engine, scfDependency)
	appApp := app.NewApp(engine, routes)
	return appApp, nil
}
