import { Resource } from '../entity/resource';
import { getRepository } from 'typeorm';

export async function resource(vars: any) {
  await getRepository(Resource).insert([
    {
      key: 'system',
      parent: 'origin',
      name: { zh_cn: '系统设置', en_us: 'System' },
      nav: 1,
      router: 0,
      policy: 0,
      icon: 'setting',
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'control',
      parent: 'system',
      name: { zh_cn: '控制授权', en_us: 'Control' },
      nav: 1,
      router: 0,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'acl-index',
      parent: 'control',
      name: { zh_cn: '访问项', en_us: 'Acl' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'acl-add',
      parent: 'acl-index',
      name: { zh_cn: '访问项新增', en_us: 'Acl Add' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'acl-edit',
      parent: 'acl-index',
      name: { zh_cn: '访问项修改', en_us: 'Acl Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'resource-index',
      parent: 'control',
      name: { zh_cn: '资源项', en_us: 'Resource' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'resource-add',
      parent: 'resource-index',
      name: { zh_cn: '资源项新增', en_us: 'Resource Add' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'resource-edit',
      parent: 'resource-index',
      name: { zh_cn: '资源项修改', en_us: 'Resource Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'permission-index',
      parent: 'system',
      name: { zh_cn: '特殊授权', en_us: 'Permission' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'permission-add',
      parent: 'permission-index',
      name: { zh_cn: '特殊授权新增', en_us: 'Permission Add' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'permission-edit',
      parent: 'permission-index',
      name: { zh_cn: '特殊授权修改', en_us: 'Permission Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'role-index',
      parent: 'system',
      name: { zh_cn: '权限组', en_us: 'Role' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'role-add',
      parent: 'role-index',
      name: { zh_cn: '权限组新增', en_us: 'Role Add' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'role-edit',
      parent: 'role-index',
      name: { zh_cn: '权限组修改', en_us: 'Role Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'admin-index',
      parent: 'system',
      name: { zh_cn: '管理员', en_us: 'Admin' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'admin-add',
      parent: 'admin-index',
      name: { zh_cn: '管理员新增', en_us: 'Admin Add' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'admin-edit',
      parent: 'admin-index',
      name: { zh_cn: '管理员修改', en_us: 'Admin Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'logger',
      parent: 'system',
      name: { zh_cn: '日志审计', en_us: 'Log Audit' },
      nav: 1,
      router: 0,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'request-log',
      parent: 'logger',
      name: { zh_cn: '访问日志', en_us: 'Request Log' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'login-log',
      parent: 'logger',
      name: { zh_cn: '登录日志', en_us: 'Login Log' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'center',
      parent: 'origin',
      name: { zh_cn: '个人中心', en_us: 'Center' },
      nav: 0,
      router: 0,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'profile',
      parent: 'center',
      name: { zh_cn: '信息修改', en_us: 'Profile' },
      nav: 0,
      router: 1,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'cms',
      parent: 'origin',
      name: { zh_cn: '内容管理', en_us: 'CMS' },
      nav: 1,
      router: 0,
      policy: 0,
      icon: 'table',
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'media',
      parent: 'cms',
      name: { zh_cn: '多媒体管理', en_us: 'Media' },
      nav: 1,
      router: 0,
      policy: 0,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'media/picture',
      parent: 'media',
      name: { zh_cn: '图片素材', en_us: 'Picture' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'media/video',
      parent: 'media',
      name: { zh_cn: '视频素材', en_us: 'Video' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'media/audio',
      parent: 'media',
      name: { zh_cn: '音频素材', en_us: 'Audio' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: null,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'page/platform',
      parent: 'cms',
      name: { zh_cn: '平台介绍', en_us: 'Platform' },
      nav: 1,
      router: 1,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'shop-index',
      parent: 'origin',
      name: { zh_cn: '商户管理', en_us: 'Shop' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: 'shop',
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'shop-add',
      parent: 'shop-index',
      name: { zh_cn: '商户新增', en_us: 'Shop Add' },
      nav: 0,
      router: 1,
      policy: 0,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'shop-edit',
      parent: 'shop-index',
      name: { zh_cn: '商户编辑', en_us: 'Shop Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'product-index',
      parent: 'shop-index',
      name: { zh_cn: '产品管理', en_us: 'Product' },
      nav: 1,
      router: 1,
      policy: 1,
      icon: 'shop',
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'product-add',
      parent: 'product-index',
      name: { zh_cn: '产品新增', en_us: 'Product Add' },
      nav: 0,
      router: 1,
      policy: 0,
      create_time: vars.time,
      update_time: vars.time,
    },
    {
      key: 'product-edit',
      parent: 'product-index',
      name: { zh_cn: '产品编辑', en_us: 'Product Edit' },
      nav: 0,
      router: 1,
      policy: 0,
      create_time: vars.time,
      update_time: vars.time,
    },
  ]);
}
